kind: helm-release
apiVersion: 1.0
build:
  context: ..\..
  dockerfile: Dockerfile
install:
  chart: charts/asamanager
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    image:
      tag: $(tag)
      pullPolicy: Never
    disableProbes: true
    ingress:
      hosts:
      # This expands to [space.s.]webservice.<guid>.<region>.aksapp.io
      - $(spacePrefix)asamanager$(hostSuffix)
       
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
    container:
      syncTarget: /src
      sync:
      - "**/Pages/**"
      - "**/Views/**"
      - "**/wwwroot/**"
      - "!**/*.{sln,csproj.sh}"
      command:  ["sh", "/src/asa-manager/WebService/azds_entrypoint.sh"]
      iterate:
        processesToKill: [dotnet, vsdbg]
        buildCommands:
        - [dotnet, build, --no-restore, -c, "${Configuration:-Debug}"]
