# Usage:
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - run `docker-compose up`

version: "3"

services:
  iothubmanager:
    image: azureiotpcs/iothub-manager-dotnet
    ports:
      - "9002:9002"
    environment:
      - PCS_IOTHUBMANAGER_WEBSERVICE_PORT
      - PCS_IOTHUB_CONNSTRING
  devicesimulation:
    image: azureiotpcs/iothub-manager-dotnet
    depends_on:
      - iothubmanager
    ports:
      - "9003:9003"
    environment:
      - PCS_DEVICESIMULATION_WEBSERVICE_PORT
      - $PCS_IOTHUBMANAGER_WEBSERVICE_URL